---
- name: copy job template
  template:
    src: identity.nomad
    dest: /tmp/identity.nomad

- name: "Performing '{{ step | default('job') }}' on Nomad {{ nomad_bind_addr }}"
  command: nomad run -address="http://{{ nomad_bind_addr }}:{{ nomad_ports_http }}" /tmp/identity.nomad
  run_once: true

- name: wait 20s
  wait_for:
    timeout: 20
