---
- hosts: localhost
  gather_facts: true
  connection: local
  vars:
    consul_use_upstart: false
    consul_use_systemd: true
    consul_bootstrap: true
    consul_datacenter: "Olymp"
    consul_is_ui: true
    consul_is_server: true
    consul_bind_address: "{{ ansible_default_ipv4['address'] }}"
    consul_node_name: "{{ ansible_hostname }}"
    #consul_servers: ['127.0.0.1']
    # TODO Remove this hardcoded part
    consul_domain: "fpdev.co."
    consul_encrypt: "cg8StVXbQJ0gPvMd9o7yrg=="
  roles:
  - savagegus.consul
  post_tasks:
  - name: delete default nginx site
    shell: rm -f /etc/nginx/sites-enabled/default
  - name: reload nginx config
    service: name=nginx state=reloaded