---
- hosts: all
  roles:
  - setup-facts

- hosts: nomad-servers
  remote_user: root
  gather_facts: true
  sudo: true
  vars:
    version_old: latest
    version_new: latest
  roles:
  - role: blue-green-deploy
