---
- hosts: all
  remote_user: root
  gather_facts: No
  sudo: True
  tasks:
  - name: install missing python2 package
    raw: sudo apt-get -y install python

- hosts: all
  remote_user: root
  gather_facts: True
  sudo: True
  vars:
    docker_admin_users:
    - docker
    docker_swarm_interface: "eth0"
    docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"
  roles:
  - djalexd.docker-swarm
  - docker-tls
  pre_tasks:
  - apt: update_cache=yes
    when: ansible_os_family == 'Debian'
  - yum: update_cache=yes
    when: ansible_os_family == 'RedHat'