---
- hosts: all
  roles:
  - setup-facts

- hosts: consul-servers, consul-clients
  remote_user: root
  sudo: true
  roles:
  - savagegus.consul
  post_tasks:
  - name: delete default nginx site
    shell: rm -f /etc/nginx/sites-enabled/default
  - name: reload nginx config
    service: name=nginx state=reloaded

- hosts: workers
  remote_user: root
  sudo: true
  gather_facts: true
  roles:
  - angstwad.docker_ubuntu

- hosts: nomad-servers
  remote_user: root
  sudo: true
  roles:
  - role: kbrebanov.nomad

- hosts: nomad-clients
  remote_user: root
  sudo: true
  roles:
  - role: kbrebanov.nomad

- hosts: lbs
  remote_user: root
  sudo: true
  roles:
  - geerlingguy.nginx
  - configure-lb
  - role: wunzeco.consul-template
    consul_template_template:
      source: "/usr/local/etc/consul-templates/upstreams.tmpl"
      destination: "/etc/nginx/sites-enabled/upstreams"
      command: "service nginx reload"
