---
- hosts: all
  remote_user: root
  sudo: true
  gather_facts: true
  vars:
    docker_admin_users:
    - docker
    docker_swarm_interface: "eth1"
    docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"  
  roles:
  - atosatto.docker-swarm