# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/debian-8.5"

  config.vm.define "jenkins" do |jenkins|
    config.vm.network "forwarded_port", guest: 8080, host: 9090
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
    # Using shell to copy the Docker configuration to
    # VM and also build it there. In a more complex setup,
    # building Jenkins (/image) should be a separate task itself
    # (maybe even use packer.io to achieve it)
    config.vm.provision "file", source: "my-jenkins-on-docker", destination: "/tmp/jenkins-image"

    # Do regular ansible provisioning
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.galaxy_role_file = "galaxy.roles"
    end
  end

  config.vm.define "dev" do |dev|
    dev.vm.network "private_network", ip: "192.168.50.10"
    dev.vm.provider "virtualbox" do |v|
      v.memory = 768
    end

    dev.vm.provision "ansible" do |ansible|
      ansible.playbook = "env.yml"
      ansible.galaxy_role_file = "galaxy.roles"
    end
  end
end
